# Generated by Django 6.0 on 2026-05-16 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('bobot', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Pengirim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Perihal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hal', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sifat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sumbersurat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Surat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_surat', models.CharField(max_length=100, unique=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='surat/')),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('tanggal_surat', models.DateField()),
                ('pengirim', models.CharField(blank=True, max_length=200, null=True)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('perihal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.perihal')),
                ('sifat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sifat')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.status')),
            ],
        ),
        migrations.CreateModel(
            name='Disposisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catatan', models.TextField(blank=True, default='')),
                ('tujuan', models.CharField(choices=[('Staff', 'Staff'), ('Kasubbid1', 'Kasubbid 1'), ('Kasubbid2', 'Kasubbid 2'), ('Kasubbid3', 'Kasubbid 3 / Jafung'), ('Kabid', 'Kabid'), ('Arsip', 'Arsip')], default='Staff', max_length=100)),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('surat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='disposisi', to='core.surat')),
            ],
        ),
    ]
