# Generated by Django 6.0 on 2026-05-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_surat_sumber_surat_alter_surat_pengirim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disposisi',
            name='tujuan',
            field=models.CharField(blank=True, choices=[('Staf', 'Staf'), ('Kasubbid 1', 'Kasubbid 1'), ('Kasubbid 2', 'Kasubbid 2'), ('Kasubbid 3', 'Kasubbid 3 / Jafung'), ('Kabid', 'Kabid'), ('Arsip', 'Arsip')], max_length=100, null=True),
        ),
    ]
