# Generated by Django 6.0 on 2026-05-16 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hasil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferensi', models.FloatField()),
                ('ranking', models.IntegerField()),
                ('surat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.surat')),
            ],
        ),
        migrations.CreateModel(
            name='Nilai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai', models.FloatField(blank=True, null=True)),
                ('kriteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.kriteria')),
                ('surat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.surat')),
            ],
        ),
    ]
